routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* Route::get('/', function () {
    return view('welcome');
}); */

Route::get('/', 'WebController@index')->name('index');
Route::get('/plan', 'WebController@plan')->name('plan');
Route::get('/tos', 'WebController@tos')->name('tos');
Route::get('/login', 'WebController@login')->name('login');
Route::post('/login', 'WebController@loginc')->name('loginc');
Route::get('/reg', 'WebController@reg')->name('reg');
Route::post('/reg', 'WebController@regc')->name('regc');
Route::get('/logout', 'WebController@logout')->name('logout');

Route::prefix('/member')->middleware('isLogin')->group(function () {
	Route::get('/', 'MemberController@center')->name('member');
	Route::prefix('/api')->middleware('can:view-api')->group(function (){
        Route::get('/', 'ApiController@show')->name('Api.show');
        Route::get('/doc', 'ApiController@doc')->name('Api.doc');
        Route::get('/apply', 'ApiController@apply')->name('Api.apply');
        Route::post('/apply', 'ApiController@applyc')->name('Api.applyc');
    });
	Route::get('/order/pay', 'MemberController@showOrderPayFrom')->name('member.showOrderPayFrom');
	Route::get('/order/get', 'MemberController@showOrderPayTo')->name('member.showOrderPayTo');
});
Route::prefix('/wallet')->middleware('isLogin')->group(function () {
	Route::get('/', 'WalletController@show')->name('wallet');
	Route::get('/redeem', 'WalletController@redeem')->name('wallet.redeem');
	Route::post('/redeem', 'WalletController@redeemc')->name('wallet.redeemc');
	Route::get('/log', 'WalletController@WalletLog')->name('wallet.log');
});

Route::prefix('/admin')->middleware('isLogin:admin')->group(function () {
	Route::get('/', 'AdminController@admin')->name('admin');
	Route::resource('/user', 'Admin\UserController');
	Route::get('/addcode', 'AdminController@AddCode')->name('admin.addCode');
	Route::post('/addcode', 'AdminController@AddCodec')->name('admin.addCodec');
});

Route::prefix('/pay')->group(function () {
	Route::post('/', 'PayController@doPay')->name('pay');
});

Route::prefix('/find')->group(function () {
	Route::post('/', 'PayController@doFind')->name('find');
});

/* Route::group(['prefix' => 'test'], function () {
	Route::get('/', 'TestController@ajax')->name('test.ajax');
	Route::post('/', 'TestController@ajaxc')->name('test.ajaxc');
	Route::get('/show', 'TestController@show')->name('test.show');
}); */

//Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'level', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
	
	public function Wallet()
	{
		return $this->hasOne(Wallet::class);
	}
	
	public function Api()
	{
		return $this->hasOne(Api::class);
	}
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\UserRepository;

class UserController extends Controller
{
    protected $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user.index', [
			'users' => $this->userRepository->paginate(10),
		]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.user.edit', [
			'user' => $this->userRepository->getById($id)
		]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->userRepository->update($id, [
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'level' => $request->input('level'),
            'status' => $request->input('status'),
        ]);
		
		return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->userRepository->delete($id);
		
		return redirect()->route('user.index');
    }
}

resources/views/admin/user/edit.blade.php
@extends('tpl-admin.main')

@section('title', '管理中心 - 編輯用戶')

@section('content')
			<form action="{{ route('user.update', [ 'user' => $user->id] ) }}" method="post" role="form">
				<div class="row">
					<div class="col-xs-4 col-md-4 mx-auto">
						<div class="form-group">
							<label for="id">使用者ID:</label>
							<input type="text" name="id" id="id" class="form-control" aria-describedby="helpBlock" value="{{ $user->id }}" readonly>
							<span class="help-block" id="helpBlock">e.g. 1 => ken(管理員)</span>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-4 col-md-4 mx-auto">
						<div class="form-group">
							<label for="name">用戶名:</label>
							<input type="text" name="name" id="name" class="form-control" value="{{ $user->name }}">
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-4 col-md-4 mx-auto">
						<div class="form-group">
							<label for="email">電郵:</label>
							<input type="text" name="email" id="email" class="form-control" value="{{ $user->email }}">
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-4 col-md-4 mx-auto">
						<div class="form-group">
							<label for="level">等級:</label>
							<select class="form-control" name="level" id="level">
								@if($user->level == 'admin')
									<option value="admin" selected>管理員(目前狀態)</option>
									<option value="store">商店會員</option>
									<option value="user">一般會員</option>
								@elseif($user->level == 'store')
									<option value="admin">管理員</option>
									<option value="store" selected>商店會員(目前狀態)</option>
									<option value="user">一般會員</option>
								@else
									<option value="admin">管理員</option>
									<option value="store">商店會員</option>
									<option value="user" selected>一般會員(目前狀態)</option>
								@endif
							</select>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-4 col-md-4 mx-auto">
						<div class="form-group">
							<label for="status">狀態:</label>
							<select class="form-control" name="status" id="status">
								@if($user->status == 1)
									<option value="1" selected>有效(目前狀態)</option>
									<option value="0">無效</option>
								@else
									<option value="1">有效</option>
									<option value="0" selected>無效(目前狀態)</option>
								@endif
							</select>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-4 col-md-4 mx-auto">
						<div class="form-group">
							<label for="created_at">註冊於:</label>
							<input type="text" name="created_at" id="created_at" class="form-control" value="{{ $user->created_at }}" readonly>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-xs-4 col-md-4 mx-auto">
						<button type="submit" class="btn btn-warning">編輯</button>
					</div>
				</div>
				@method('PATCH')
				@csrf
			</form>
@endsection

resources/views/admin/user/index.blade.php
@extends('tpl-admin.main')

@section('title', '管理中心 - 用戶列表')

@section('head')
	<script>
		function check()
		{
			return confirm('您確定要移除該帳號嗎？(此動作不可回逆！)');
		}
	</script>
@endsection

@section('content')
		<table class="table table-bordered">
			<tr>
				<td>編號</td>
				<td>帳號</td>
				<td>電郵</td>
				<td>等級</td>
				<td>狀態</td>
				<td>註冊於</td>
				<td>編輯</td>
				<td>刪除</td>
			</tr>
			@foreach($users as $user)
				<tr>
					<td>{{ $user->id }}</td>
					<td>{{ $user->name }}</td>
					<td>{{ $user->email }}</td>
					@if($user->level == 'root')
						<td><span class="badge badge-success">Root</span></td>
					@elseif($user->level == 'admin')
						<td><span class="badge badge-success">管理員</span></td>
					@elseif($user->level == 'store')
						<td><span class="badge badge-success">商店會員</span></td>
					@elseif($user->level == 'user')
						<td><span class="badge badge-success">一般會員</span></td>
					@else
						<td><span class="badge badge-warning">有問題</span></td>
					@endif
					@if($user->status == 1)
						<td><span class="badge badge-success">有效</span></td>
					@else
						<td><span class="badge badge-danger">無效</span></td>
					@endif
					<td>{{ $user->created_at }}</td>
					@if($user->level == 'root')
						<td colspan="2"><span class="badge badge-info">不能更動</span></td>
					@else
						<td>
							<a href="{{ route('user.edit', [ 'user' => $user->id]) }}" class="btn btn-warning">編輯</a>
						</td>
						<td>
							<form action="{{ route('user.destroy', ['user' => $user->id ]) }}" method="post" class="form-inline" role="form" onsubmit="return check()">
								@method('DELETE')
								@csrf
								<button type="submit" class="btn btn-danger">移除</button>
							</form>
						</td>
					@endif
				</tr>
			@endforeach
		</table>
		{{ $users->links() }}
@endsection